name: .NET Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server/Ordo

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Publish .NET App
      if: github.event_name == 'push'
      run: dotnet publish --no-build --configuration Release --output ./publish-folder

    - name: Upload Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v6
      with:
        name: ordo-backend-artifact
        path: ${{ github.workspace }}/server/Ordo/publish-folder


  deploy:
    if: github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v7
      with:
        name: ordo-backend-artifact
        path: ./publish-folder

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'ordo-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish-folder
